[doc]
name = "presentation"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"

[[output]]
name = "introduction"
type = "pdf"
shell_escape = true
# inputs = "introduction/main.tex"
preamble = ""
index = "introduction/main.tex"
postamble = ""

[[output]]
name = "packages"
type = "pdf"
shell_escape = true
# inputs = "packages/main.tex"
preamble = ""
index = "packages/main.tex"
postamble = ""
