[doc]
name = "presentation"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"

[[output]]
name = "introduction"
type = "pdf"
shell_escape = true
shell_escape_cwd = "src"
# inputs = "introduction/main.tex"
preamble = ""
index = "main.tex"
postamble = ""
