---
name: latex
on:
  push:
    tags: "*-*-*"
    paths:
      - 'presentation/**'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./presentation
    steps:
      - uses: actions/checkout@v4
      - uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: compile packages presentation
        run: cd packages && tectonic -X build
      - name: compile introduction presentation
        run: cd introduction && tectonic -X build
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            presentation/introduction/build/introduction/introduction.pdf
            presentation/packages/build/packages/packages.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
